# Generated by Django 3.1.7 on 2021-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='des',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='des',
            field=models.TextField(max_length=500),
        ),
    ]
